### ISSUE TITLE
When receiving an APDU response from device with only status bytes, error is returned

### ISSUE THREAD

**Issue by yogh333** [ledger-community/rust-ledger#4]
I think that `status bytes` shall be checked before returning an error, as, in some case, an APDU response with no data but status bytes = `0x9000` is correct. My proposal to fix this is to modify `Generic [Device] implementation for types supporting [Exchange]` as following:

```diff
diff --git a/lib/src/device.rs b/lib/src/device.rs
index f7b951c..a97e4c4 100644
--- a/lib/src/device.rs
+++ b/lib/src/device.rs
@@ -89,8 +89,8 @@ impl<T: Exchange + Send> Device for T {
         }
         buff[..n].copy_from_slice(&resp_bytes[..]);

-        // Handle error responses (2 bytes long, only a status)
-        if n == 2 {
+        // Handle error responses (2 bytes long, status bytes != 0x9000)
+        if n == 2 && resp_bytes[0] != 0x90 && resp_bytes[1] != 0x00 {
             return Err(Error::Response(resp_bytes[0], resp_bytes[1]));
         }
```

**Comment by ryankurte** [comment]
yep, at the moment if you're expecting a okay status you have to write something like:
```rust
let mut buff = [0u8; 256];
let resp = d
    .request::<GenericApdu>(RunAppReq::new(&app_name), &mut buff, args.timeout.into())
    .await;

match resp {
    Ok(_) | Err(Error::Response(0x90, 0x00))=> println!("App open!"),
    Err(Error::EmptyResponse) => println!("Timeout waiting for approval"),
    Err(e) => println!("Command failed: {e:?}"),
}
```

> I think that status bytes shall be checked before returning an error, as, in some case, an APDU response with no data but status bytes = 0x9000 is correct

so the reason that isn't checked as you propose is that if you have a 0 byte response you don't want to call `RESP::decode` over a zero length buffer, so it depends whether we can tell whether a response will have a body at compile time or not?

if you break down the logic there are 4 possible states:

- request failed -> Error
- request ok, error response (APDU status) -> Error
- request ok, nil response (with APDU status) -> ApduStatus
- request ok, apdu response (with APDU status) -> (Resp, ApduStatus)

if we can say whether a response will or will not have a body _at compile time_ we can reduce the last two states so you call either `request::<RESP>()` or `request::<StatusBytes>()`, in which case the patch you propose would work nicely.

otherwise there are a few options to represent this with different tradeoffs...
- `Result<(Option<Resp>, ApduStatus), Error>` would let you return okay status separate from error status and not call `RESP::decode` for zero length responses, but makes calling this more annoying for all cases
- A custom `Result` enum could actually represent all the options, but would be incompatible with standard error handling
- `Result<Resp, Error>` where `Error` contains `ApduResponse` (the current approach), okay responses are represented as an error, but, it's pretty easy to match on this for cases where this should be handled

**Comment by yogh333** [comment]
> yep, at the moment if you're expecting a okay status you have to write something like:
> 
> ```rust
> let mut buff = [0u8; 256];
> let resp = d
>     .request::<GenericApdu>(RunAppReq::new(&app_name), &mut buff, args.timeout.into())
>     .await;
> 
> match resp {
>     Ok(_) | Err(Error::Response(0x90, 0x00))=> println!("App open!"),
>     Err(Error::EmptyResponse) => println!("Timeout waiting for approval"),
>     Err(e) => println!("Command failed: {e:?}"),
> }
> ```

Okay with this

> 
> > I think that status bytes shall be checked before returning an error, as, in some case, an APDU response with no data but status bytes = 0x9000 is correct
> 
> so the reason that isn't checked as you propose is that if you have a 0 byte response you don't want to call `RESP::decode` over a zero length buffer, so it depends whether we can tell whether a response will have a body at compile time or not?
> 
> if you break down the logic there are 4 possible states:
> 
> * request failed -> Error
> * request ok, error response (APDU status) -> Error
> * request ok, nil response (with APDU status) -> ApduStatus
> * request ok, apdu response (with APDU status) -> (Resp, ApduStatus)
> 
> if we can say whether a response will or will not have a body _at compile time_ we can reduce the last two states so you call either `request::<RESP>()` or `request::<StatusBytes>()`, in which case the patch you propose would work nicely.
> 

Knowing if a response will have a body or not _at_compile_time_  is not generic and future-proof, it fully depends on the request APDU content and the target application running on the device.  

> otherwise there are a few options to represent this with different tradeoffs...
> 
> * `Result<(Option<Resp>, ApduStatus), Error>` would let you return okay status separate from error status and not call `RESP::decode` for zero length responses, but makes calling this more annoying for all cases
> * A custom `Result` enum could actually represent all the options, but would be incompatible with standard error handling
> * `Result<Resp, Error>` where `Error` contains `ApduResponse` (the current approach), okay responses are represented as an error, but, it's pretty easy to match on this for cases where this should be handled

Okay so I agree that the last proposal (current approach) is the best: handling of empty response with StatusBytes = 0x9000 can be efficiently managed by CLI (as you explain above). One might also about future use cases where an app might return StatusBytes != 9000 but with a non-empty body (if it makes sense...)
